version: "3.3"
services:
  web:
    container_name: app
    build: .
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"